omnia_ipsum:
    images:
        default_provider: 'picsum'
        default_width: 600
        default_height: 400

    videos:
        default_provider: 'gcs'
        default_width: 1920
        default_height: 1080
        default_duration: 30

    audios:
        default_provider: 'soundhelix'
        default_duration: 10

    text:
        default_paragraphs: 3
        default_sentences: 5
        default_words: 50

    faker:
        locale: 'en_US'
        seed: null

